export const data = [
  {
    id: 1,
    name: "Pizza Hut",
    type: "italian",
    img: "https://images.pexels.com/photos/3915857/pexels-photo-3915857.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    rating: 0,
    menu: {
      pizza: [
        {
          id: 100,
          name: " Pizza Capriciosa",
          desc: "Tomato sauce, mozzarella, Milanese salami, ham, mushrooms, olives",
          img: "https://images.unsplash.com/photo-1617219474299-b17c6a43834d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=779&q=80",
          price: 30,
          isFav: false,
        },
        {
          id: 101,
          name: " Pizza Quattro Formagi",
          desc: "Tomato sauce, mozzarella, Milano salami, cabanos, olives, ham, onion, mushrooms, corn",
          img: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80",
          price: 37.3,
          isFav: false,
        },
        {
          id: 102,
          name: " Pizza Diavola",
          desc: "Tomato sauce, mozzarella, mushrooms, Sicilian salami, olives, anchovies",
          img: "https://properpizza.ro/rmvalcea/wp-content/uploads/2020/03/Proper-Pizza-Pasta-Diavola-00.jpg",
          price: 41,
          isFav: false,
        },
        {
          id: 103,
          name: "Pizza Prosciutto Crudo",
          desc: "Tomato sauce, mozzarella, Milano salami, mushrooms, olives",
          img: "https://wips.plug.it/cips/buonissimo.org/cms/2011/12/pizza-al-prosciutto-crudo.jpg?w=712&a=c&h=406",
          price: 41,
          isFav: false,
        },
      ],
      chicken: [
        {
          id: 104,
          name: "Chicken schnitzel in parmesan crust",
          desc: "Chicken breast, parmesan, egg, flour 200g",
          img: "https://simply-delicious-food.com/wp-content/uploads/2019/07/Pecorino-crumbed-chicken-4.jpg",
          price: 28,
          isFav: false,
        },
        {
          id: 105,
          name: "Hot chicken croquettes",
          desc: "Chicken breast, breadcrumbs, flour, chilli flakes, sour cream with garlic 300g",
          img: "https://cuban.recipes/wp-content/uploads//2019/04/chicken-croquettes-1024x1024.jpg",
          price: 35,
          isFav: false,
        },
      ],
      dessert: [
        {
          id: 143,
          name: "Biscuit salami",
          desc: "Cocoa, cookies, raisins, turkish delight, butter, black belgian chocolate, natural whipped cream, rum 100g",
          img: "https://www.thesouthafrican.com/wp-content/uploads/2020/08/e444e627-chocolate-biscuit-salami-recipe-1.jpg",
          price: 12,
          isFav: false,
        },
        {
          id: 144,
          name: "Nocciola cake",
          desc: "cocoa dough, white belgian chocolate mousse, caramel with peanuts",
          img: "https://media.lacucinaitaliana.com/photos/5e9deceece78a60008d606c9/1:1/pass/torta%20nocciola.jpg",
          price: 23,
          isFav: false,
        },
        {
          id: 145,
          name: "Diplomat Special Jack Daniel's",
          desc: "thin vanila top, vanilla cream with peach and pineapple, vanilla cream with caramel, vanilla cream with forest fruits",
          img: "https://i2.wp.com/mygorgeousrecipes.com/wp-content/uploads/2017/12/Charlotte-Cake-15.jpg",
          price: 26,
          isFav: false,
        },
        {
          id: 146,
          name: "Pancakes with chocolate",
          desc: "Tasty pancakes with homemade chocholate",
          img: "https://inthekitchenwithmatt.com/wp-content/uploads/2020/01/Chocolate-Pancakes.jpg",
          price: 13,
          isFav: false,
        },
      ],
    },
  },
  {
    id: 2,
    name: "Wuu Muu",
    type: "chinese",
    img: "https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    rating: 0,
    menu: {
      chicken: [
        {
          id: 106,
          name: " Shanghai Chicken",
          desc: "chicken meat, breadcrumbs, flour, salt, chinese spices - 220g",
          img: "https://lincontro.ro/wp-content/uploads/2022/01/pui_shanghai.jpg",
          price: 23.46,
          isFav: false,
        },
        {
          id: 107,
          name: " Spicy Shanghai Chicken",
          desc: "chicken meat, flour, chilli pepper paste, spicy paprika, chinese spices, salt - 220g",
          img: "http://food-market.ro/wp-content/uploads/2020/05/Pui-Shangai-1.jpg",
          price: 24.6,
          isFav: false,
        },
        {
          id: 108,
          name: " Chicken with mushrooms",
          desc: "chicken, fresh mushrooms, onion, wood ears, green onion, garlic, sesame oil, sugar, sunflower oil, salt, corn/tapioca starch - 300g",
          img: "https://cdn3.tmbi.com/toh/GoogleImagesPostCard/Baked-Chicken-and-Mushrooms_EXPS_DSBZ17_22740_B01_13_4b.jpg",
          price: 22.9,
          isFav: false,
        },
        {
          id: 109,
          name: "Hot chicken with potatoes",
          desc: "chicken meat, fried chips, garlic, green onion, pul biber spice, sweet paprika, sunflower oil, salt, chinese spices - 250g",
          img: "https://embed.widencdn.net/img/mccormick/qkunma3mdf/1365x1365px/Rosemary%20Baked%20Chicken%20with%20Potatoes_2019-04-10_9052_TSUCALAS.jpg?crop=true&anchor=212,0&q=80&color=ffffffff&u=o2hyef",
          price: 22.9,
          isFav: false,
        },
      ],
      pork: [
        {
          id: 110,
          name: "Pork with pineapple",
          desc: "pork meat, pineapple, bell pepper, carrots, sweet and sour sauce, sunflower oil, starch 300g",
          img: "https://www.bbcgoodfoodme.com/assets/legacy/recipe_images/recipe-image-legacy-id--338556_11.jpg",
          price: 23.5,
          isFav: false,
        },
        {
          id: 111,
          name: "Pork with wooden ear mushrooms",
          desc: "pork meat, carrots, cucumbers, spring onion, wooden ear mushrooms, egg, sunflower oil, garlic, salt 300g",
          img: "https://thewoksoflife.com/wp-content/uploads/2013/07/pork-pepper-wood-ear.jpg",
          price: 24,
          isFav: false,
        },
      ],
    },
  },
  {
    id: 3,
    name: "El puerto",
    type: "seafood",
    img: "https://images.pexels.com/photos/842142/pexels-photo-842142.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    rating: 0,
    menu: {
      chicken: [
        {
          id: 112,
          name: " Chicken roll with gorgonzola",
          desc: "chicken breast, potatoes, cheese, flour, gorgonzola, liquid sour cream, mushrooms 550g",
          img: "http://www.italianfoodforever.com/wp-content/uploads/2010/01/stuffedchicken.jpg",
          price: 35,
          isFav: false,
        },
        {
          id: 113,
          name: " Chicken schnitzel",
          desc: "hicken breast, milk, eggs, flour, breadcrumbs 160g",
          img: "https://www.thespruceeats.com/thmb/1Ntqkrw7h6LagewLYRvqflUli6A=/2848x2848/smart/filters:no_upscale()/wiener-schnitzel-recipe-1447089-Hero-5b587d6c46e0fb0071b0059d.jpg",
          price: 21,
          isFav: false,
        },
        {
          id: 114,
          name: " Chicken legs with smooth garlic sauce and mashed potatoes",
          desc: "chicken legs, potatoes, flour, milk, liquid sour cream, garlic 200g",
          img: "https://previews.123rf.com/images/serezniy/serezniy1206/serezniy120602860/14084576-roasted-chicken-leg-with-mashed-potato-in-the-plate-on-wooden-table-close-up.jpg",
          price: 31,
          isFav: false,
        },
        {
          id: 115,
          name: " Spicy chicken wings",
          desc: "chicken wings, potatoes, eros spicy paste, barbeque sauce 400g",
          img: "https://hips.hearstapps.com/hmg-prod/images/classic-buffalo-wings-horizontal-279-1547506077.jpg",
          price: 32,
          isFav: false,
        },
      ],
      pork: [
        {
          id: 116,
          name: "Grilled pork neck",
          desc: "pork neck 170g",
          img: "https://i.ytimg.com/vi/YLhX_zGxSBw/maxresdefault.jpg",
          price: 23,
          isFav: false,
        },
        {
          id: 117,
          name: "Pork knuckles with cabbage",
          desc: "pork meat with bone, smoked sausages, onion, savory, smoked bacon, tomatoes pasta, dill, mustard, pickled cabbage 750g",
          img: "https://previews.123rf.com/images/voltan1/voltan11811/voltan1181100011/113130172-roasted-pork-knuckle-with-braised-cabbage-sauerkraut-and-mustard-on-black-stone-background-with-copy.jpg",
          price: 43,
          isFav: false,
        },
      ],
      fish: [
        {
          id: 118,
          name: "Grilled carp",
          desc: "salmon, broccoli, baby carrot, butter 180g/200g",
          img: "https://previews.123rf.com/images/lenyvavsha/lenyvavsha1504/lenyvavsha150400130/39225685-fried-carp-with-lemon-onion-and-spices-on-a-black-grill-pan-horizontal-top-view-close-up.jpg",
          price: 52,
          isFav: false,
        },
        {
          id: 119,
          name: "Grilled salmon with vegetables",
          desc: "carp, lemon 180g",
          img: "https://cheeseman1.com/wp-content/uploads/2016/11/Grilled-Salmon-and-Vegetables.jpg",
          price: 31,
          isFav: false,
        },
        {
          id: 120,
          name: "Grilled Nile zander fillet",
          desc: "Nile zander, lemon 300g",
          img: "https://images.eatsmarter.com/sites/default/files/styles/576x432/public/perch-fillet-with-spinach-567732.jpg",
          price: 37,
          isFav: false,
        },
      ],
    },
  },
  {
    id: 4,
    name: "Tratoria Buongiorno",
    type: "italian",
    img: "https://images.pexels.com/photos/4748540/pexels-photo-4748540.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    rating: 0,
    menu: {
      pasta: [
        {
          id: 121,
          name: " Pollo Pasta with white sauce",
          desc: "Chicken breast, mushrooms, white sauce, garlic 350g",
          img: "https://www.licious.in/blog/wp-content/uploads/2020/12/Chicken-White-sauce-pasta.jpg",
          price: 27,
          isFav: false,
        },
        {
          id: 122,
          name: " Quattro Formaggi Pasta",
          desc: "Gorgonzola, asiago, taleggio, parmesan 350g",
          img: "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2017/11/penne-ai-quattro-formaggi/jcr:content/imagePreview.img10.jpg/1511979074060.jpg",
          price: 28.5,
          isFav: false,
        },
        {
          id: 123,
          name: " Ragu Bolognese Marilu Pasta",
          desc: "Minced pork and beef meat, carrot, apio celery, onion, tomato sauce 350g",
          img: "https://thecozyapron.com/wp-content/uploads/2019/05/spaghetti-bolognese_thecozyapron_1.jpg",
          price: 27,
          isFav: false,
        },
        {
          id: 124,
          name: "Tonno E Olive Spaghetti",
          desc: "Spaghetti, tuna, green olives, tomatoes sauce, parmesan 350g",
          img: "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2018/02/3481_Fusilli.jpg?resize=895%2C616&ssl=1",
          price: 32,
          isFav: false,
        },
      ],
      rice: [
        {
          id: 125,
          name: "Risotto with saffron",
          desc: "Rice, saffron, eggplants, bell pepper, mushrooms 300g",
          img: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/saffron-risotto-a0e9b8d.jpg?quality=90&resize=430,390",
          price: 21,
          isFav: false,
        },
        {
          id: 126,
          name: "Risotto Frutti di Mare",
          desc: "Rice, seafood, shrimps, greens 300g",
          img: "https://img.taste.com.au/slxRSMID/w720-h480-cfill-q80/taste/2016/11/seafood-risotto-39585-1.jpeg",
          price: 35,
          isFav: false,
        },
      ],
    },
  },
  {
    id: 5,
    name: "Fratellionos",
    type: "seafood",
    img: "https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    rating: 0,
    menu: {
      pasta: [
        {
          id: 132,
          name: " Tagliatelle ai funghi porcini",
          desc: "pasta, porcini, white sauce",
          img: "https://www.scattidigusto.it/wp-content/uploads/2020/09/tagliatelle-ai-funghi-porcini.jpg",
          price: 30,
          isFav: false,
        },
        {
          id: 133,
          name: " Penne pugliese",
          desc: "pasta, prosciutto crudo, spinach, white sauce",
          img: "https://www.mangiarepugliese.com/wp-content/uploads/2018/03/IMG_86391-e1520587288852-1024x768.jpg",
          price: 25,
          isFav: false,
        },
        {
          id: 134,
          name: " Tortellini al forno",
          desc: "Tortellini al forno",
          img: "https://www.kitchennostalgia.com/images2/pasta/tortellini-al-forno1-w.jpg",
          price: 30,
          isFav: false,
        },
        {
          id: 135,
          name: "Tagliatelle con vegetale",
          desc: "pasta, zucchini, eggplant, apio, pink sauce, parmesan",
          img: "https://wips.plug.it/cips/buonissimo.org/cms/2012/06/tagliatelle-alle-verdure.jpg",
          price: 29,
          isFav: false,
        },
      ],
      fish: [
        {
          id: 136,
          name: "Gamberi con vino bianco/cognac",
          desc: "shrimp with white wine sauce/cognac 430g",
          img: "https://cdn.shopify.com/s/files/1/0374/4592/6957/products/Gamberidell_Atlanticoconsalsadiburro_aglioevinobianco_1000x.jpg?v=1585066188",
          price: 43.8,
          isFav: false,
        },
        {
          id: 137,
          name: "Calamari alla griglia/fritti",
          desc: "grilled/fried calamari 380g",
          img: "https://images.lacucinaitaliana.it/wp-content/uploads/2017/08/Calamari-ripieni-alla-griglia.jpg",
          price: 32,
          isFav: false,
        },
        {
          id: 138,
          name: "Orata alla mediterranea",
          desc: "bream in the oven with cherry tomato, black olive, garlic and capers, nature potatoes 500g",
          img: "https://www.ricettedalmondo.it/images/foto-ricette/f/31207-filetti-di-orata-alla-mediterranea.jpg",
          price: 35,
          isFav: false,
        },
        {
          id: 139,
          name: "Tonno alla griglia",
          desc: "grilled red tuna fillet, nature potatoes 380g",
          img: "https://www.agrodolce.it/app/uploads/2016/05/tonno-alla-piastra.jpg",
          price: 51,
          isFav: false,
        },
      ],

      dessert: [
        {
          id: 140,
          name: "Profiterol della casa",
          desc: "classsic italian profiterol",
          img: "https://www.gustos.ro/assets/recipes_images/2016/11/24/227343/tn4_the_one.jpg",
          price: 19,
          isFav: false,
        },
        {
          id: 141,
          name: "Torta con biscotti",
          desc: "crunchy biscuits with chocholate cream",
          img: "https://bucataria-universala.com/wp-content/uploads/2018/02/tort-de-biscuiti-fara-coacere.jpg",
          price: 18,
          isFav: false,
        },
        {
          id: 142,
          name: "Tiramisu",
          desc: "Cocoa, coffee, instant coffee, mascarpone, lady fingers, natural whipped cream, charlotte 100g",
          img: "https://retete.unica.ro/wp-content/uploads/2010/11/Tiramisu-cu-crem%C4%83-mascarpone.jpg",
          price: 15,
          isFav: false,
        },
      ],
    },
  },
  {
    id: 6,
    name: "Peng Yang",
    type: "chinese",
    img: "https://cdn.pixabay.com/photo/2015/04/10/00/41/food-715542_1280.jpg",
    rating: 0,
    menu: {
      pasta: [
        {
          id: 133,
          name: " Ants in a tree dish",
          desc: "rice pasta,vegetables,soy sauce",
          img: "https://cdn.i-scmp.com/sites/default/files/styles/1920x1080/public/d8/images/2020/02/12/mer61930379.jpg?itok=iFCWZNIw",
          price: 24,
          isFav: false,
        },
        {
          id: 134,
          name: " Spaghetti with Jumbo shrimps and vegetables",
          desc: "rice spagetti with jumbo shrimps",
          img: "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Shrimp-Pasta-Primavera_EXPS_CF2BZ20_22380_E12_05_5b.jpg",
          price: 32,
          isFav: false,
        },
        {
          id: 135,
          name: " Fried spaghetti with chicken",
          desc: "rice spagetti with chicken",
          img: "https://www.preciouscore.com/wp-content/uploads/2020/03/spaghetti-stir-fry-recipe.jpg",
          price: 29,
          isFav: false,
        },
        {
          id: 136,
          name: "Kuey Teow Shrimps- Clams- Sausages, with noodles rice",
          desc: "noodles with Kuey Teow Shrimps- Clams",
          img: "https://rasamalaysia.com/wp-content/uploads/2009/11/char-koay-teow-thumb.jpg",
          price: 33,
          isFav: false,
        },
      ],
      pork: [
        {
          id: 137,
          name: "Spicy chopped pork meat cooked on the stove",
          desc: "Spicy chopped pork meat cooked on the stove",
          img: "https://twosleevers.com/wp-content/uploads/2019/03/Chili-pork-overhead-680x900.jpg",
          price: 38,
          isFav: false,
        },
        {
          id: 138,
          name: "Chinese Garden pork meat",
          desc: "Chinese Garden pork meat 380g",
          img: "https://cookingwithdog.com/wp-content/uploads/2021/04/pork-char-siu-00.jpg",
          price: 32,
          isFav: false,
        },
        {
          id: 139,
          name: "Pork meat with wooden ears mushrooms",
          desc: "Pork meat with wooden ears mushrooms 320g",
          img: "http://lh3.ggpht.com/mwsKN1czErMG1Lg082a3VzNLHz935vtqUjz27HsQSSbR6SFdr7RWVeatzyR6LbB7jpaAL_E-HbQc18bAQsQ6ojG51A=s800",
          price: 33,
          isFav: false,
        },
        {
          id: 140,
          name: "Gan Bian pork ribs",
          desc: "pork ribs with vegetables and chinese sauce 380g",
          img: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F868083.jpg",
          price: 40,
          isFav: false,
        },
      ],

      rice: [
        {
          id: 141,
          name: "Rice with shrimp",
          desc: "Rice, eggs, corn, green peas, carrot, seafood, salt, chinese seasonings 250g",
          img: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F19%2F2012%2F04%2F10%2Fshrimp-fried-rice-ck-x.jpg&q=85",
          price: 19,
          isFav: false,
        },
        {
          id: 142,
          name: "Yang Zhou rice",
          desc: "Rice, smoked chicken breast, eggs, corn, green peas, carrots, salt, chinese spices 250g",
          img: "http://www.yumofchina.com/wp-content/uploads/2017/06/Yangzhou-fried-rice11.jpg",
          price: 17.5,
          isFav: false,
        },
        {
          id: 143,
          name: "Curry rice",
          desc: "Rice, eggs, corn, green peas, carrot, curry, salt, chinese seasonings 250g",
          img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/curry-rice-horizontal-4-jpg-1597858591.jpg?crop=0.668xw:1.00xh;0.332xw,0&resize=480:*",
          price: 15.22,
          isFav: false,
        },
      ],
    },
  },
];
export default data;
